// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID   int64
	Name string
	Desc sql.NullString
}

type Sighting struct {
	ID        int64
	FeedID    int64
	CreatedAt time.Time
	Title     sql.NullString
	Summary   sql.NullString
	Lat       float64
	Long      float64
}
