// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (name, desc) VALUES (?, ?)
RETURNING id, name, "desc"
`

type CreateFeedParams struct {
	Name string
	Desc sql.NullString
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.Name, arg.Desc)
	var i Feed
	err := row.Scan(&i.ID, &i.Name, &i.Desc)
	return i, err
}

const createSighting = `-- name: CreateSighting :one

INSERT INTO sightings (
  created_at, title, summary, lat, long, feed_id
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, feed_id, created_at, title, summary, lat, long
`

type CreateSightingParams struct {
	CreatedAt string
	Title     sql.NullString
	Summary   sql.NullString
	Lat       float64
	Long      float64
	FeedID    int64
}

// Sightings CRUD
func (q *Queries) CreateSighting(ctx context.Context, arg CreateSightingParams) (Sighting, error) {
	row := q.db.QueryRowContext(ctx, createSighting,
		arg.CreatedAt,
		arg.Title,
		arg.Summary,
		arg.Lat,
		arg.Long,
		arg.FeedID,
	)
	var i Sighting
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.CreatedAt,
		&i.Title,
		&i.Summary,
		&i.Lat,
		&i.Long,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds
WHERE id = ?
`

func (q *Queries) DeleteFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const deleteSighting = `-- name: DeleteSighting :exec
DELETE FROM sightings
WHERE id = ?
`

func (q *Queries) DeleteSighting(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSighting, id)
	return err
}

const getFeedByID = `-- name: GetFeedByID :one
SELECT id, name, desc FROM feeds
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetFeedByID(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, id)
	var i Feed
	err := row.Scan(&i.ID, &i.Name, &i.Desc)
	return i, err
}

const getSighting = `-- name: GetSighting :one
SELECT id, feed_id, created_at, title, summary, lat, long FROM sightings
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSighting(ctx context.Context, id int64) (Sighting, error) {
	row := q.db.QueryRowContext(ctx, getSighting, id)
	var i Sighting
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.CreatedAt,
		&i.Title,
		&i.Summary,
		&i.Lat,
		&i.Long,
	)
	return i, err
}

const listAllFeeds = `-- name: ListAllFeeds :many
SELECT id, name, desc FROM feeds
ORDER BY name
`

func (q *Queries) ListAllFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(&i.ID, &i.Name, &i.Desc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSightings = `-- name: ListSightings :many
SELECT id, feed_id, created_at, title, summary, lat, long FROM sightings
WHERE
  lat >= ?
  AND lat <= ?
  AND long >= ?
  AND lat <= ?
  AND created_at >= ?
  AND created_at <= ?
  AND feed_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListSightingsParams struct {
	Lat         float64
	Lat_2       float64
	Long        float64
	Lat_3       float64
	CreatedAt   string
	CreatedAt_2 string
	FeedID      int64
	Limit       int64
}

func (q *Queries) ListSightings(ctx context.Context, arg ListSightingsParams) ([]Sighting, error) {
	rows, err := q.db.QueryContext(ctx, listSightings,
		arg.Lat,
		arg.Lat_2,
		arg.Long,
		arg.Lat_3,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.FeedID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sighting
	for rows.Next() {
		var i Sighting
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.CreatedAt,
			&i.Title,
			&i.Summary,
			&i.Lat,
			&i.Long,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :exec
UPDATE feeds
SET name = ?,
    desc = ?
WHERE id = ?
`

type UpdateFeedParams struct {
	Name string
	Desc sql.NullString
	ID   int64
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) error {
	_, err := q.db.ExecContext(ctx, updateFeed, arg.Name, arg.Desc, arg.ID)
	return err
}

const updateSighting = `-- name: UpdateSighting :exec
UPDATE sightings
SET created_at = ?,
    title = ?,
    summary = ?,
    lat = ?,
    long = ?
WHERE id = ?
`

type UpdateSightingParams struct {
	CreatedAt string
	Title     sql.NullString
	Summary   sql.NullString
	Lat       float64
	Long      float64
	ID        int64
}

func (q *Queries) UpdateSighting(ctx context.Context, arg UpdateSightingParams) error {
	_, err := q.db.ExecContext(ctx, updateSighting,
		arg.CreatedAt,
		arg.Title,
		arg.Summary,
		arg.Lat,
		arg.Long,
		arg.ID,
	)
	return err
}
